FROM python:3.12-slim

WORKDIR /app

# Install system dependencies untuk psycopg2 (Postgres) dan build tools
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    git \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000